app:
  github:
    token: ${GITHUB_TOKEN} # env variable
    base-url: "https://api.github.com"
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    base-url: "https://api.stackexchange.com/2.3"
  bot-url: "http://localhost:8080"
spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/link_update
    username: admin
    password: 111111
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      pool-name: MyHikariPool
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

#logging:
#  structured:
#    format:
#      console: ecs
