version: '3.8'


services:
  liquibase-migrations:
    container_name: migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    volumes:
      - ./migrations:/changesets
    command:
      - --searchPath=/changesets
      - --changeLogFile=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/link_update
      - --username=admin
      - --password=111111
      - update


  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: link_update
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
